import os
import json
import datetime
from openai import AzureOpenAI
from dotenv import load_dotenv
import ast

# Load environment variables
load_dotenv()

# Initialize the Azure OpenAI client
client = AzureOpenAI(
    azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
    api_key=os.getenv("AZURE_OPENAI_API_KEY"),
    api_version="2024-02-01"
)

# Function to fetch flight information
def get_flight_info(loc_origin: str, loc_destination: str):
    flight_info = {
        "location_origin": loc_origin,
        "location_destination": loc_destination,
        "date_time": str(datetime.datetime.now() + datetime.timedelta(hours=2)),
        "airline_name": "Southwest Airlines",
        "flight": "Airbus738"
    }
    return json.dumps(flight_info)

# Function descriptions for the OpenAI API tool
function_descriptions = [
    {
        "name": "get_flight_info",
        "description": "Get flight information between two locations",
        "parameters": {
            "type": "object",
            "properties": {
                "loc_origin": {"type": "string", "description": "Departure airport, e.g., LAX"},
                "loc_destination": {"type": "string", "description": "Destination airport, e.g., DEL"},
            },
            "required": ["loc_origin", "loc_destination"],
        },
        "type": "function"
    }
]

# User's prompt
user_prompt = "When is the next flight from longbeach to Delhi?"

# API call to OpenAI with the correct parameters
response = client.chat.completions.create(
    model="gpt-4o",  # Model name typo fixed (ensure this is correct)
    messages=[{"role": "user", "content": user_prompt}],
    functions=function_descriptions, 
    function_call="auto",  
)

# Get the function name and arguments from OpenAI's response
function_name = response.choices[0].message.function_call.name
choosen_function = eval(function_name)  # This is safe if the function is already defined
print(choosen_function)

# Parse the arguments (arguments are a JSON string)
params = json.loads(response.choices[0].message.function_call.arguments)

# Call the function with the arguments
flight_info = choosen_function(**params)
print(flight_info)

# Now make a second call to OpenAI with the flight info
final_response = client.chat.completions.create(
    model="gpt-4o", 
    messages=[
        {"role": "user", "content": user_prompt},
        {"role": "function", "name": function_name, "content": flight_info},
        {"role": "system", "content": "The following flight information is accurate and generated by a system. It is not real-time, but it is a valid flight schedule."}
    ]
)


# Print the response from GPT after passing the flight info
print(final_response.choices[0].message.content)
